class ZCL_ZAPI_BUSINESS_PART_MPC definition
  public
  inheriting from /IWBEP/CL_MGW_PUSH_ABS_MODEL
  create public .

public section.

  types:
  begin of TS_A_ADDRESSEMAILADDRESSTYPE,
     ADDRESSID type C length 10,
     PERSON type C length 10,
     ORDINALNUMBER type C length 3,
     ISDEFAULTEMAILADDRESS type FLAG,
     EMAILADDRESS type C length 241,
     SEARCHEMAILADDRESS type C length 20,
     ADDRESSCOMMUNICATIONREMARKTEXT type C length 50,
  end of TS_A_ADDRESSEMAILADDRESSTYPE .
  types:
TT_A_ADDRESSEMAILADDRESSTYPE type standard table of TS_A_ADDRESSEMAILADDRESSTYPE .
  types:
   begin of ts_text_element,
      artifact_name  type c length 40,       " technical name
      artifact_type  type c length 4,
      parent_artifact_name type c length 40, " technical name
      parent_artifact_type type c length 4,
      text_symbol    type textpoolky,
   end of ts_text_element .
  types:
         tt_text_elements type standard table of ts_text_element with key text_symbol .
  types:
  begin of TS_A_ADDRESSFAXNUMBERTYPE,
     ADDRESSID type C length 10,
     PERSON type C length 10,
     ORDINALNUMBER type C length 3,
     ISDEFAULTFAXNUMBER type FLAG,
     FAXCOUNTRY type C length 3,
     FAXNUMBER type C length 30,
     FAXNUMBEREXTENSION type C length 10,
     INTERNATIONALFAXNUMBER type C length 30,
     ADDRESSCOMMUNICATIONREMARKTEXT type C length 50,
  end of TS_A_ADDRESSFAXNUMBERTYPE .
  types:
TT_A_ADDRESSFAXNUMBERTYPE type standard table of TS_A_ADDRESSFAXNUMBERTYPE .
  types:
  begin of TS_A_ADDRESSHOMEPAGEURLTYPE,
     ADDRESSID type C length 10,
     PERSON type C length 10,
     ORDINALNUMBER type C length 3,
     VALIDITYSTARTDATE type TIMESTAMP,
     ISDEFAULTURLADDRESS type FLAG,
     SEARCHURLADDRESS type C length 50,
     ADDRESSCOMMUNICATIONREMARKTEXT type C length 50,
     URLFIELDLENGTH type /IWBEP/SB_ODATA_TY_INT2,
     WEBSITEURL type C length 2048,
  end of TS_A_ADDRESSHOMEPAGEURLTYPE .
  types:
TT_A_ADDRESSHOMEPAGEURLTYPE type standard table of TS_A_ADDRESSHOMEPAGEURLTYPE .
  types:
  begin of TS_A_ADDRESSPHONENUMBERTYPE,
     ADDRESSID type C length 10,
     PERSON type C length 10,
     ORDINALNUMBER type C length 3,
     DESTINATIONLOCATIONCOUNTRY type C length 3,
     ISDEFAULTPHONENUMBER type FLAG,
     PHONENUMBER type C length 30,
     PHONENUMBEREXTENSION type C length 10,
     INTERNATIONALPHONENUMBER type C length 30,
     PHONENUMBERTYPE type C length 1,
     ADDRESSCOMMUNICATIONREMARKTEXT type C length 50,
  end of TS_A_ADDRESSPHONENUMBERTYPE .
  types:
TT_A_ADDRESSPHONENUMBERTYPE type standard table of TS_A_ADDRESSPHONENUMBERTYPE .
  types:
  begin of TS_A_BPADDRDEPDNTINTLLOCNUMBER,
     BUSINESSPARTNER type C length 10,
     ADDRESSID type C length 10,
     INTERNATIONALLOCATIONNUMBER1 type C length 7,
     INTERNATIONALLOCATIONNUMBER2 type C length 5,
     INTERNATIONALLOCATIONNUMBER3 type C length 1,
  end of TS_A_BPADDRDEPDNTINTLLOCNUMBER .
  types:
TT_A_BPADDRDEPDNTINTLLOCNUMBER type standard table of TS_A_BPADDRDEPDNTINTLLOCNUMBER .
  types:
  begin of TS_A_BPCONTACTTOADDRESSTYPE,
     RELATIONSHIPNUMBER type C length 12,
     BUSINESSPARTNERCOMPANY type C length 10,
     BUSINESSPARTNERPERSON type C length 10,
     VALIDITYENDDATE type TIMESTAMP,
     ADDRESSID type C length 10,
     ADDRESSNUMBER type C length 10,
     ADDITIONALSTREETPREFIXNAME type C length 40,
     ADDITIONALSTREETSUFFIXNAME type C length 40,
     ADDRESSTIMEZONE type C length 6,
     CAREOFNAME type C length 40,
     CITYCODE type C length 12,
     CITYNAME type C length 40,
     COMPANYPOSTALCODE type C length 10,
     COUNTRY type C length 3,
     COUNTY type C length 40,
     DELIVERYSERVICENUMBER type C length 10,
     DELIVERYSERVICETYPECODE type C length 4,
     DISTRICT type C length 40,
     FORMOFADDRESS type C length 4,
     FULLNAME type C length 80,
     HOMECITYNAME type C length 40,
     HOUSENUMBER type C length 10,
     HOUSENUMBERSUPPLEMENTTEXT type C length 10,
     LANGUAGE type C length 2,
     POBOX type C length 10,
     POBOXDEVIATINGCITYNAME type C length 40,
     POBOXDEVIATINGCOUNTRY type C length 3,
     POBOXDEVIATINGREGION type C length 3,
     POBOXISWITHOUTNUMBER type FLAG,
     POBOXLOBBYNAME type C length 40,
     POBOXPOSTALCODE type C length 10,
     PERSON type C length 10,
     POSTALCODE type C length 10,
     PRFRDCOMMMEDIUMTYPE type C length 3,
     REGION type C length 3,
     STREETNAME type C length 60,
     STREETPREFIXNAME type C length 40,
     STREETSUFFIXNAME type C length 40,
     TAXJURISDICTION type C length 15,
     TRANSPORTZONE type C length 10,
     ADDRESSREPRESENTATIONCODE type C length 1,
     CONTACTRELATIONSHIPFUNCTION type C length 40,
     CONTACTRELATIONSHIPDEPARTMENT type C length 40,
     FLOOR type C length 10,
     CONTACTPERSONBUILDING type C length 10,
     ROOMNUMBER type C length 10,
     CONTACTPERSONPRFRDCOMMMEDIUM type C length 3,
     CORRESPONDENCESHORTNAME type C length 10,
     INHOUSEMAIL type C length 10,
  end of TS_A_BPCONTACTTOADDRESSTYPE .
  types:
TT_A_BPCONTACTTOADDRESSTYPE type standard table of TS_A_BPCONTACTTOADDRESSTYPE .
  types:
  begin of TS_A_BPCONTACTTOFUNCANDDEPTTYP,
     RELATIONSHIPNUMBER type C length 12,
     BUSINESSPARTNERCOMPANY type C length 10,
     BUSINESSPARTNERPERSON type C length 10,
     VALIDITYENDDATE type TIMESTAMP,
     CONTACTPERSONFUNCTION type C length 4,
     CONTACTPERSONDEPARTMENT type C length 4,
     PHONENUMBER type C length 30,
     PHONENUMBEREXTENSION type C length 10,
     FAXNUMBER type C length 30,
     FAXNUMBEREXTENSION type C length 10,
     EMAILADDRESS type C length 241,
     RELATIONSHIPCATEGORY type C length 6,
  end of TS_A_BPCONTACTTOFUNCANDDEPTTYP .
  types:
TT_A_BPCONTACTTOFUNCANDDEPTTYP type standard table of TS_A_BPCONTACTTOFUNCANDDEPTTYP .
  types:
  begin of TS_A_BUPAADDRESSUSAGETYPE,
     BUSINESSPARTNER type C length 10,
     VALIDITYENDDATE type TIMESTAMP,
     ADDRESSUSAGE type C length 10,
     ADDRESSID type C length 10,
     VALIDITYSTARTDATE type TIMESTAMP,
     STANDARDUSAGE type FLAG,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUPAADDRESSUSAGETYPE .
  types:
TT_A_BUPAADDRESSUSAGETYPE type standard table of TS_A_BUPAADDRESSUSAGETYPE .
  types:
  begin of TS_A_BUPAIDENTIFICATIONTYPE,
     BUSINESSPARTNER type C length 10,
     BPIDENTIFICATIONTYPE type C length 6,
     BPIDENTIFICATIONNUMBER type C length 60,
     BPIDNNMBRISSUINGINSTITUTE type C length 40,
     BPIDENTIFICATIONENTRYDATE type TIMESTAMP,
     COUNTRY type C length 3,
     REGION type C length 3,
     VALIDITYSTARTDATE type TIMESTAMP,
     VALIDITYENDDATE type TIMESTAMP,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUPAIDENTIFICATIONTYPE .
  types:
TT_A_BUPAIDENTIFICATIONTYPE type standard table of TS_A_BUPAIDENTIFICATIONTYPE .
  types:
  begin of TS_A_BUPAINDUSTRYTYPE,
     INDUSTRYSECTOR type C length 10,
     INDUSTRYSYSTEMTYPE type C length 4,
     BUSINESSPARTNER type C length 10,
     ISSTANDARDINDUSTRY type C length 1,
     INDUSTRYKEYDESCRIPTION type C length 100,
  end of TS_A_BUPAINDUSTRYTYPE .
  types:
TT_A_BUPAINDUSTRYTYPE type standard table of TS_A_BUPAINDUSTRYTYPE .
  types:
  begin of TS_A_BUSPARTADDRDEPDNTTAXNMBRT,
     BUSINESSPARTNER type C length 10,
     ADDRESSID type C length 10,
     BPTAXTYPE type C length 4,
     BPTAXNUMBER type C length 20,
     BPTAXLONGNUMBER type C length 60,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUSPARTADDRDEPDNTTAXNMBRT .
  types:
TT_A_BUSPARTADDRDEPDNTTAXNMBRT type standard table of TS_A_BUSPARTADDRDEPDNTTAXNMBRT .
  types:
  begin of TS_A_BUSINESSPARTNERADDRESSTYP,
     BUSINESSPARTNER type C length 10,
     ADDRESSID type C length 10,
     VALIDITYSTARTDATE type TIMESTAMP,
     VALIDITYENDDATE type TIMESTAMP,
     AUTHORIZATIONGROUP type C length 4,
     ADDRESSUUID type SYSUUID_X,
     ADDITIONALSTREETPREFIXNAME type C length 40,
     ADDITIONALSTREETSUFFIXNAME type C length 40,
     ADDRESSTIMEZONE type C length 6,
     CAREOFNAME type C length 40,
     CITYCODE type C length 12,
     CITYNAME type C length 40,
     COMPANYPOSTALCODE type C length 10,
     COUNTRY type C length 3,
     COUNTY type C length 40,
     DELIVERYSERVICENUMBER type C length 10,
     DELIVERYSERVICETYPECODE type C length 4,
     DISTRICT type C length 40,
     FORMOFADDRESS type C length 4,
     FULLNAME type C length 80,
     HOMECITYNAME type C length 40,
     HOUSENUMBER type C length 10,
     HOUSENUMBERSUPPLEMENTTEXT type C length 10,
     LANGUAGE type C length 2,
     POBOX type C length 10,
     POBOXDEVIATINGCITYNAME type C length 40,
     POBOXDEVIATINGCOUNTRY type C length 3,
     POBOXDEVIATINGREGION type C length 3,
     POBOXISWITHOUTNUMBER type FLAG,
     POBOXLOBBYNAME type C length 40,
     POBOXPOSTALCODE type C length 10,
     PERSON type C length 10,
     POSTALCODE type C length 10,
     PRFRDCOMMMEDIUMTYPE type C length 3,
     REGION type C length 3,
     STREETNAME type C length 60,
     STREETPREFIXNAME type C length 40,
     STREETSUFFIXNAME type C length 40,
     TAXJURISDICTION type C length 15,
     TRANSPORTZONE type C length 10,
     ADDRESSIDBYEXTERNALSYSTEM type C length 20,
     COUNTYCODE type C length 8,
     TOWNSHIPCODE type C length 8,
     TOWNSHIPNAME type C length 40,
  end of TS_A_BUSINESSPARTNERADDRESSTYP .
  types:
TT_A_BUSINESSPARTNERADDRESSTYP type standard table of TS_A_BUSINESSPARTNERADDRESSTYP .
  types:
  begin of TS_A_BUSINESSPARTNERBANKTYPE,
     BUSINESSPARTNER type C length 10,
     BANKIDENTIFICATION type C length 4,
     BANKCOUNTRYKEY type C length 3,
     BANKNAME type C length 60,
     BANKNUMBER type C length 15,
     SWIFTCODE type C length 11,
     BANKCONTROLKEY type C length 2,
     BANKACCOUNTHOLDERNAME type C length 60,
     BANKACCOUNTNAME type C length 40,
     VALIDITYSTARTDATE type TIMESTAMP,
     VALIDITYENDDATE type TIMESTAMP,
     IBAN type C length 34,
     IBANVALIDITYSTARTDATE type TIMESTAMP,
     BANKACCOUNT type C length 18,
     BANKACCOUNTREFERENCETEXT type C length 20,
     COLLECTIONAUTHIND type FLAG,
     CITYNAME type C length 35,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUSINESSPARTNERBANKTYPE .
  types:
TT_A_BUSINESSPARTNERBANKTYPE type standard table of TS_A_BUSINESSPARTNERBANKTYPE .
  types:
  begin of TS_A_BUSINESSPARTNERCONTACTTYP,
     RELATIONSHIPNUMBER type C length 12,
     BUSINESSPARTNERCOMPANY type C length 10,
     BUSINESSPARTNERPERSON type C length 10,
     VALIDITYENDDATE type TIMESTAMP,
     VALIDITYSTARTDATE type TIMESTAMP,
     ISSTANDARDRELATIONSHIP type FLAG,
     RELATIONSHIPCATEGORY type C length 6,
  end of TS_A_BUSINESSPARTNERCONTACTTYP .
  types:
TT_A_BUSINESSPARTNERCONTACTTYP type standard table of TS_A_BUSINESSPARTNERCONTACTTYP .
  types:
  begin of TS_A_BUSINESSPARTNERROLETYPE,
     BUSINESSPARTNER type C length 10,
     BUSINESSPARTNERROLE type C length 6,
     VALIDFROM type TIMESTAMP,
     VALIDTO type TIMESTAMP,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUSINESSPARTNERROLETYPE .
  types:
TT_A_BUSINESSPARTNERROLETYPE type standard table of TS_A_BUSINESSPARTNERROLETYPE .
  types:
  begin of TS_A_BUSINESSPARTNERTAXNUMBERT,
     BUSINESSPARTNER type C length 10,
     BPTAXTYPE type C length 4,
     BPTAXNUMBER type C length 20,
     BPTAXLONGNUMBER type C length 60,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_BUSINESSPARTNERTAXNUMBERT .
  types:
TT_A_BUSINESSPARTNERTAXNUMBERT type standard table of TS_A_BUSINESSPARTNERTAXNUMBERT .
  types:
  begin of TS_A_BUSINESSPARTNERTYPE,
     BUSINESSPARTNER type C length 10,
     CUSTOMER type C length 10,
     SUPPLIER type C length 10,
     ACADEMICTITLE type C length 4,
     AUTHORIZATIONGROUP type C length 4,
     BUSINESSPARTNERCATEGORY type C length 1,
     BUSINESSPARTNERFULLNAME type C length 81,
     BUSINESSPARTNERGROUPING type C length 4,
     BUSINESSPARTNERNAME type C length 81,
     BUSINESSPARTNERUUID type SYSUUID_X,
     CORRESPONDENCELANGUAGE type C length 2,
     CREATEDBYUSER type C length 12,
     CREATIONDATE type TIMESTAMP,
     CREATIONTIME type T,
     FIRSTNAME type C length 40,
     FORMOFADDRESS type C length 4,
     INDUSTRY type C length 10,
     INTERNATIONALLOCATIONNUMBER1 type C length 7,
     INTERNATIONALLOCATIONNUMBER2 type C length 5,
     ISFEMALE type FLAG,
     ISMALE type FLAG,
     ISNATURALPERSON type C length 1,
     ISSEXUNKNOWN type FLAG,
     GENDERCODENAME type C length 1,
     LANGUAGE type C length 2,
     LASTCHANGEDATE type TIMESTAMP,
     LASTCHANGETIME type T,
     LASTCHANGEDBYUSER type C length 12,
     LASTNAME type C length 40,
     LEGALFORM type C length 2,
     ORGANIZATIONBPNAME1 type C length 40,
     ORGANIZATIONBPNAME2 type C length 40,
     ORGANIZATIONBPNAME3 type C length 40,
     ORGANIZATIONBPNAME4 type C length 40,
     ORGANIZATIONFOUNDATIONDATE type TIMESTAMP,
     ORGANIZATIONLIQUIDATIONDATE type TIMESTAMP,
     SEARCHTERM1 type C length 20,
     SEARCHTERM2 type C length 20,
     ADDITIONALLASTNAME type C length 40,
     BIRTHDATE type TIMESTAMP,
     BUSINESSPARTNERBIRTHDATESTATUS type C length 1,
     BUSINESSPARTNERBIRTHPLACENAME type C length 40,
     BUSINESSPARTNERDEATHDATE type TIMESTAMP,
     BUSINESSPARTNERISBLOCKED type FLAG,
     BUSINESSPARTNERTYPE type C length 4,
     ETAG type C length 26,
     GROUPBUSINESSPARTNERNAME1 type C length 40,
     GROUPBUSINESSPARTNERNAME2 type C length 40,
     INDEPENDENTADDRESSID type C length 10,
     INTERNATIONALLOCATIONNUMBER3 type C length 1,
     MIDDLENAME type C length 40,
     NAMECOUNTRY type C length 3,
     NAMEFORMAT type C length 2,
     PERSONFULLNAME type C length 80,
     PERSONNUMBER type C length 10,
     ISMARKEDFORARCHIVING type FLAG,
     BUSINESSPARTNERIDBYEXTSYSTEM type C length 20,
     BUSINESSPARTNERPRINTFORMAT type C length 1,
     BUSINESSPARTNEROCCUPATION type C length 4,
     BUSPARTMARITALSTATUS type C length 1,
     BUSPARTNATIONALITY type C length 3,
     BUSINESSPARTNERBIRTHNAME type C length 40,
     BUSINESSPARTNERSUPPLEMENTNAME type C length 4,
     NATURALPERSONEMPLOYERNAME type C length 35,
     LASTNAMEPREFIX type C length 4,
     LASTNAMESECONDPREFIX type C length 4,
     INITIALS type C length 10,
     TRADINGPARTNER type C length 6,
  end of TS_A_BUSINESSPARTNERTYPE .
  types:
TT_A_BUSINESSPARTNERTYPE type standard table of TS_A_BUSINESSPARTNERTYPE .
  types:
  begin of TS_A_CUSTADDRDEPDNTEXTIDENTIFI,
     CUSTOMER type C length 10,
     ADDRESSID type C length 10,
     CUSTOMEREXTERNALREFID type C length 12,
  end of TS_A_CUSTADDRDEPDNTEXTIDENTIFI .
  types:
TT_A_CUSTADDRDEPDNTEXTIDENTIFI type standard table of TS_A_CUSTADDRDEPDNTEXTIDENTIFI .
  types:
  begin of TS_A_CUSTADDRDEPDNTINFORMATION,
     CUSTOMER type C length 10,
     ADDRESSID type C length 10,
     EXPRESSTRAINSTATIONNAME type C length 25,
     TRAINSTATIONNAME type C length 25,
     CITYCODE type C length 4,
     COUNTY type C length 3,
  end of TS_A_CUSTADDRDEPDNTINFORMATION .
  types:
TT_A_CUSTADDRDEPDNTINFORMATION type standard table of TS_A_CUSTADDRDEPDNTINFORMATION .
  types:
  begin of TS_A_CUSTSALESPARTNERFUNCTYPE,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     PARTNERCOUNTER type C length 3,
     PARTNERFUNCTION type C length 2,
     BPCUSTOMERNUMBER type C length 10,
     CUSTOMERPARTNERDESCRIPTION type C length 30,
     DEFAULTPARTNER type FLAG,
     SUPPLIER type C length 10,
     PERSONNELNUMBER type C length 8,
     CONTACTPERSON type C length 10,
     ADDRESSID type C length 10,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_CUSTSALESPARTNERFUNCTYPE .
  types:
TT_A_CUSTSALESPARTNERFUNCTYPE type standard table of TS_A_CUSTSALESPARTNERFUNCTYPE .
  types:
  begin of TS_A_CUSTSLSAREAADDRDEPDNTINFO,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     ADDRESSID type C length 10,
     INCOTERMSCLASSIFICATION type C length 3,
     INCOTERMSLOCATION1 type C length 70,
     INCOTERMSLOCATION2 type C length 70,
     DELIVERYISBLOCKED type C length 2,
     SALESOFFICE type C length 4,
     SALESGROUP type C length 3,
     SHIPPINGCONDITION type C length 2,
     SUPPLYINGPLANT type C length 4,
     INCOTERMSVERSION type C length 4,
  end of TS_A_CUSTSLSAREAADDRDEPDNTINFO .
  types:
TT_A_CUSTSLSAREAADDRDEPDNTINFO type standard table of TS_A_CUSTSLSAREAADDRDEPDNTINFO .
  types:
  begin of TS_A_CUSTSLSAREAADDRDEPDNTTAXI,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     ADDRESSID type C length 10,
     DEPARTURECOUNTRY type C length 3,
     CUSTOMERTAXCATEGORY type C length 4,
     CUSTOMERTAXCLASSIFICATION type C length 1,
  end of TS_A_CUSTSLSAREAADDRDEPDNTTAXI .
  types:
TT_A_CUSTSLSAREAADDRDEPDNTTAXI type standard table of TS_A_CUSTSLSAREAADDRDEPDNTTAXI .
  types:
  begin of TS_A_CUSTUNLDGPTADDRDEPDNTINFO,
     CUSTOMER type C length 10,
     ADDRESSID type C length 10,
     UNLOADINGPOINTNAME type C length 25,
     CUSTOMERFACTORYCALENDERCODE type C length 2,
     BPGOODSRECEIVINGHOURSCODE type C length 3,
     ISDFLTBPUNLOADINGPOINT type FLAG,
     MONDAYMORNINGOPENINGTIME type T,
     MONDAYMORNINGCLOSINGTIME type T,
     MONDAYAFTERNOONOPENINGTIME type T,
     MONDAYAFTERNOONCLOSINGTIME type T,
     TUESDAYMORNINGOPENINGTIME type T,
     TUESDAYMORNINGCLOSINGTIME type T,
     TUESDAYAFTERNOONOPENINGTIME type T,
     TUESDAYAFTERNOONCLOSINGTIME type T,
     WEDNESDAYMORNINGOPENINGTIME type T,
     WEDNESDAYMORNINGCLOSINGTIME type T,
     WEDNESDAYAFTERNOONOPENINGTIME type T,
     WEDNESDAYAFTERNOONCLOSINGTIME type T,
     THURSDAYMORNINGOPENINGTIME type T,
     THURSDAYMORNINGCLOSINGTIME type T,
     THURSDAYAFTERNOONOPENINGTIME type T,
     THURSDAYAFTERNOONCLOSINGTIME type T,
     FRIDAYMORNINGOPENINGTIME type T,
     FRIDAYMORNINGCLOSINGTIME type T,
     FRIDAYAFTERNOONOPENINGTIME type T,
     FRIDAYAFTERNOONCLOSINGTIME type T,
     SATURDAYMORNINGOPENINGTIME type T,
     SATURDAYMORNINGCLOSINGTIME type T,
     SATURDAYAFTERNOONOPENINGTIME type T,
     SATURDAYAFTERNOONCLOSINGTIME type T,
     SUNDAYMORNINGOPENINGTIME type T,
     SUNDAYMORNINGCLOSINGTIME type T,
     SUNDAYAFTERNOONOPENINGTIME type T,
     SUNDAYAFTERNOONCLOSINGTIME type T,
  end of TS_A_CUSTUNLDGPTADDRDEPDNTINFO .
  types:
TT_A_CUSTUNLDGPTADDRDEPDNTINFO type standard table of TS_A_CUSTUNLDGPTADDRDEPDNTINFO .
  types:
  begin of TS_A_CUSTOMERCOMPANYTEXTTYPE,
     CUSTOMER type C length 10,
     COMPANYCODE type C length 4,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_CUSTOMERCOMPANYTEXTTYPE .
  types:
TT_A_CUSTOMERCOMPANYTEXTTYPE type standard table of TS_A_CUSTOMERCOMPANYTEXTTYPE .
  types:
  begin of TS_A_CUSTOMERCOMPANYTYPE,
     CUSTOMER type C length 10,
     COMPANYCODE type C length 4,
     APARTOLERANCEGROUP type C length 4,
     ACCOUNTBYCUSTOMER type C length 12,
     ACCOUNTINGCLERK type C length 2,
     ACCOUNTINGCLERKFAXNUMBER type C length 31,
     ACCOUNTINGCLERKINTERNETADDRESS type C length 130,
     ACCOUNTINGCLERKPHONENUMBER type C length 30,
     ALTERNATIVEPAYERACCOUNT type C length 10,
     AUTHORIZATIONGROUP type C length 4,
     COLLECTIVEINVOICEVARIANT type C length 1,
     CUSTOMERACCOUNTNOTE type C length 30,
     CUSTOMERHEADOFFICE type C length 10,
     CUSTOMERSUPPLIERCLEARINGISUSED type FLAG,
     HOUSEBANK type C length 5,
     INTERESTCALCULATIONCODE type C length 2,
     INTERESTCALCULATIONDATE type TIMESTAMP,
     INTRSTCALCFREQUENCYINMONTHS type C length 2,
     ISTOBELOCALLYPROCESSED type FLAG,
     ITEMISTOBEPAIDSEPARATELY type FLAG,
     LAYOUTSORTINGRULE type C length 3,
     PAYMENTBLOCKINGREASON type C length 1,
     PAYMENTMETHODSLIST type C length 10,
     PAYMENTTERMS type C length 4,
     PAYTADVICEISSENTBYEDI type FLAG,
     PHYSICALINVENTORYBLOCKIND type FLAG,
     RECONCILIATIONACCOUNT type C length 10,
     RECORDPAYMENTHISTORYINDICATOR type FLAG,
     USERATCUSTOMER type C length 15,
     DELETIONINDICATOR type FLAG,
     CASHPLANNINGGROUP type C length 10,
     KNOWNORNEGOTIATEDLEAVE type C length 4,
     VALUEADJUSTMENTKEY type C length 2,
     CUSTOMERACCOUNTGROUP type C length 4,
  end of TS_A_CUSTOMERCOMPANYTYPE .
  types:
TT_A_CUSTOMERCOMPANYTYPE type standard table of TS_A_CUSTOMERCOMPANYTYPE .
  types:
  begin of TS_A_CUSTOMERDUNNINGTYPE,
     CUSTOMER type C length 10,
     COMPANYCODE type C length 4,
     DUNNINGAREA type C length 2,
     DUNNINGBLOCK type C length 1,
     DUNNINGLEVEL type C length 1,
     DUNNINGPROCEDURE type C length 4,
     DUNNINGRECIPIENT type C length 10,
     LASTDUNNEDON type TIMESTAMP,
     LEGDUNNINGPROCEDUREON type TIMESTAMP,
     DUNNINGCLERK type C length 2,
     AUTHORIZATIONGROUP type C length 4,
     CUSTOMERACCOUNTGROUP type C length 4,
  end of TS_A_CUSTOMERDUNNINGTYPE .
  types:
TT_A_CUSTOMERDUNNINGTYPE type standard table of TS_A_CUSTOMERDUNNINGTYPE .
  types:
  begin of TS_A_CUSTOMERSALESAREATAXTYPE,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     DEPARTURECOUNTRY type C length 3,
     CUSTOMERTAXCATEGORY type C length 4,
     CUSTOMERTAXCLASSIFICATION type C length 1,
  end of TS_A_CUSTOMERSALESAREATAXTYPE .
  types:
TT_A_CUSTOMERSALESAREATAXTYPE type standard table of TS_A_CUSTOMERSALESAREATAXTYPE .
  types:
  begin of TS_A_CUSTOMERSALESAREATEXTTYPE,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_CUSTOMERSALESAREATEXTTYPE .
  types:
TT_A_CUSTOMERSALESAREATEXTTYPE type standard table of TS_A_CUSTOMERSALESAREATEXTTYPE .
  types:
  begin of TS_A_CUSTOMERSALESAREATYPE,
     CUSTOMER type C length 10,
     SALESORGANIZATION type C length 4,
     DISTRIBUTIONCHANNEL type C length 2,
     DIVISION type C length 2,
     ACCOUNTBYCUSTOMER type C length 12,
     AUTHORIZATIONGROUP type C length 4,
     BILLINGISBLOCKEDFORCUSTOMER type C length 2,
     COMPLETEDELIVERYISDEFINED type FLAG,
     CURRENCY type C length 5,
     CUSTOMERABCCLASSIFICATION type C length 2,
     CUSTOMERACCOUNTASSIGNMENTGROUP type C length 2,
     CUSTOMERGROUP type C length 2,
     CUSTOMERPAYMENTTERMS type C length 4,
     CUSTOMERPRICEGROUP type C length 2,
     CUSTOMERPRICINGPROCEDURE type C length 2,
     DELIVERYISBLOCKEDFORCUSTOMER type C length 2,
     DELIVERYPRIORITY type C length 2,
     INCOTERMSCLASSIFICATION type C length 3,
     INCOTERMSLOCATION2 type C length 70,
     INCOTERMSVERSION type C length 4,
     INCOTERMSLOCATION1 type C length 70,
     DELETIONINDICATOR type FLAG,
     INCOTERMSTRANSFERLOCATION type C length 28,
     INVOICEDATE type C length 2,
     ITEMORDERPROBABILITYINPERCENT type C length 3,
     ORDERCOMBINATIONISALLOWED type FLAG,
     ORDERISBLOCKEDFORCUSTOMER type C length 2,
     PARTIALDELIVERYISALLOWED type C length 1,
     PRICELISTTYPE type C length 2,
     SALESGROUP type C length 3,
     SALESOFFICE type C length 4,
     SHIPPINGCONDITION type C length 2,
     SUPPLYINGPLANT type C length 4,
     SALESDISTRICT type C length 6,
     INVOICELISTSCHEDULE type C length 2,
     EXCHANGERATETYPE type C length 4,
     ADDITIONALCUSTOMERGROUP1 type C length 3,
     ADDITIONALCUSTOMERGROUP2 type C length 3,
     ADDITIONALCUSTOMERGROUP3 type C length 3,
     ADDITIONALCUSTOMERGROUP4 type C length 3,
     ADDITIONALCUSTOMERGROUP5 type C length 3,
     PAYMENTGUARANTEEPROCEDURE type C length 4,
     CUSTOMERACCOUNTGROUP type C length 4,
  end of TS_A_CUSTOMERSALESAREATYPE .
  types:
TT_A_CUSTOMERSALESAREATYPE type standard table of TS_A_CUSTOMERSALESAREATYPE .
  types:
  begin of TS_A_CUSTOMERTAXGROUPINGTYPE,
     CUSTOMER type C length 10,
     CUSTOMERTAXGROUPINGCODE type C length 3,
     CUSTTAXGRPEXEMPTIONCERTIFICATE type C length 15,
     CUSTTAXGROUPEXEMPTIONRATE type P length 3 decimals 2,
     CUSTTAXGROUPEXEMPTIONSTARTDATE type TIMESTAMP,
     CUSTTAXGROUPEXEMPTIONENDDATE type TIMESTAMP,
     CUSTTAXGROUPSUBJECTEDSTARTDATE type TIMESTAMP,
     CUSTTAXGROUPSUBJECTEDENDDATE type TIMESTAMP,
  end of TS_A_CUSTOMERTAXGROUPINGTYPE .
  types:
TT_A_CUSTOMERTAXGROUPINGTYPE type standard table of TS_A_CUSTOMERTAXGROUPINGTYPE .
  types:
  begin of TS_A_CUSTOMERTEXTTYPE,
     CUSTOMER type C length 10,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_CUSTOMERTEXTTYPE .
  types:
TT_A_CUSTOMERTEXTTYPE type standard table of TS_A_CUSTOMERTEXTTYPE .
  types:
  begin of TS_A_CUSTOMERTYPE,
     CUSTOMER type C length 10,
     AUTHORIZATIONGROUP type C length 4,
     BILLINGISBLOCKEDFORCUSTOMER type C length 2,
     CREATEDBYUSER type C length 12,
     CREATIONDATE type TIMESTAMP,
     CUSTOMERACCOUNTGROUP type C length 4,
     CUSTOMERCLASSIFICATION type C length 2,
     CUSTOMERFULLNAME type C length 220,
     CUSTOMERNAME type C length 80,
     DELIVERYISBLOCKED type C length 2,
     NFPARTNERISNATURALPERSON type C length 1,
     ORDERISBLOCKEDFORCUSTOMER type C length 2,
     POSTINGISBLOCKED type FLAG,
     SUPPLIER type C length 10,
     CUSTOMERCORPORATEGROUP type C length 10,
     FISCALADDRESS type C length 10,
     INDUSTRY type C length 4,
     INDUSTRYCODE1 type C length 10,
     INDUSTRYCODE2 type C length 10,
     INDUSTRYCODE3 type C length 10,
     INDUSTRYCODE4 type C length 10,
     INDUSTRYCODE5 type C length 10,
     INTERNATIONALLOCATIONNUMBER1 type C length 7,
     NIELSENREGION type C length 2,
     RESPONSIBLETYPE type C length 2,
     TAXNUMBER1 type C length 16,
     TAXNUMBER2 type C length 11,
     TAXNUMBER3 type C length 18,
     TAXNUMBER4 type C length 18,
     TAXNUMBER5 type C length 60,
     TAXNUMBERTYPE type C length 2,
     VATREGISTRATION type C length 20,
     DELETIONINDICATOR type FLAG,
     EXPRESSTRAINSTATIONNAME type C length 25,
     TRAINSTATIONNAME type C length 25,
     CITYCODE type C length 4,
     COUNTY type C length 3,
  end of TS_A_CUSTOMERTYPE .
  types:
TT_A_CUSTOMERTYPE type standard table of TS_A_CUSTOMERTYPE .
  types:
  begin of TS_A_CUSTOMERUNLOADINGPOINTTYP,
     CUSTOMER type C length 10,
     UNLOADINGPOINTNAME type C length 25,
     CUSTOMERFACTORYCALENDERCODE type C length 2,
     BPGOODSRECEIVINGHOURSCODE type C length 3,
     ISDFLTBPUNLOADINGPOINT type FLAG,
     MONDAYMORNINGOPENINGTIME type T,
     MONDAYMORNINGCLOSINGTIME type T,
     MONDAYAFTERNOONOPENINGTIME type T,
     MONDAYAFTERNOONCLOSINGTIME type T,
     TUESDAYMORNINGOPENINGTIME type T,
     TUESDAYMORNINGCLOSINGTIME type T,
     TUESDAYAFTERNOONOPENINGTIME type T,
     TUESDAYAFTERNOONCLOSINGTIME type T,
     WEDNESDAYMORNINGOPENINGTIME type T,
     WEDNESDAYMORNINGCLOSINGTIME type T,
     WEDNESDAYAFTERNOONOPENINGTIME type T,
     WEDNESDAYAFTERNOONCLOSINGTIME type T,
     THURSDAYMORNINGOPENINGTIME type T,
     THURSDAYMORNINGCLOSINGTIME type T,
     THURSDAYAFTERNOONOPENINGTIME type T,
     THURSDAYAFTERNOONCLOSINGTIME type T,
     FRIDAYMORNINGOPENINGTIME type T,
     FRIDAYMORNINGCLOSINGTIME type T,
     FRIDAYAFTERNOONOPENINGTIME type T,
     FRIDAYAFTERNOONCLOSINGTIME type T,
     SATURDAYMORNINGOPENINGTIME type T,
     SATURDAYMORNINGCLOSINGTIME type T,
     SATURDAYAFTERNOONOPENINGTIME type T,
     SATURDAYAFTERNOONCLOSINGTIME type T,
     SUNDAYMORNINGOPENINGTIME type T,
     SUNDAYMORNINGCLOSINGTIME type T,
     SUNDAYAFTERNOONOPENINGTIME type T,
     SUNDAYAFTERNOONCLOSINGTIME type T,
  end of TS_A_CUSTOMERUNLOADINGPOINTTYP .
  types:
TT_A_CUSTOMERUNLOADINGPOINTTYP type standard table of TS_A_CUSTOMERUNLOADINGPOINTTYP .
  types:
  begin of TS_A_CUSTOMERWITHHOLDINGTAXTYP,
     CUSTOMER type C length 10,
     COMPANYCODE type C length 4,
     WITHHOLDINGTAXTYPE type C length 2,
     WITHHOLDINGTAXCODE type C length 2,
     WITHHOLDINGTAXAGENT type FLAG,
     OBLIGATIONDATEBEGIN type TIMESTAMP,
     OBLIGATIONDATEEND type TIMESTAMP,
     WITHHOLDINGTAXNUMBER type C length 16,
     WITHHOLDINGTAXCERTIFICATE type C length 25,
     WITHHOLDINGTAXEXMPTPERCENT type P length 3 decimals 2,
     EXEMPTIONDATEBEGIN type TIMESTAMP,
     EXEMPTIONDATEEND type TIMESTAMP,
     EXEMPTIONREASON type C length 2,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_CUSTOMERWITHHOLDINGTAXTYP .
  types:
TT_A_CUSTOMERWITHHOLDINGTAXTYP type standard table of TS_A_CUSTOMERWITHHOLDINGTAXTYP .
  types:
  begin of TS_A_SUPPLIERCOMPANYTEXTTYPE,
     SUPPLIER type C length 10,
     COMPANYCODE type C length 4,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_SUPPLIERCOMPANYTEXTTYPE .
  types:
TT_A_SUPPLIERCOMPANYTEXTTYPE type standard table of TS_A_SUPPLIERCOMPANYTEXTTYPE .
  types:
  begin of TS_A_SUPPLIERCOMPANYTYPE,
     SUPPLIER type C length 10,
     COMPANYCODE type C length 4,
     AUTHORIZATIONGROUP type C length 4,
     COMPANYCODENAME type C length 25,
     PAYMENTBLOCKINGREASON type C length 1,
     SUPPLIERISBLOCKEDFORPOSTING type FLAG,
     ACCOUNTINGCLERK type C length 2,
     ACCOUNTINGCLERKFAXNUMBER type C length 31,
     ACCOUNTINGCLERKPHONENUMBER type C length 30,
     SUPPLIERCLERK type C length 15,
     SUPPLIERCLERKURL type C length 130,
     PAYMENTMETHODSLIST type C length 10,
     PAYMENTTERMS type C length 4,
     CLEARCUSTOMERSUPPLIER type FLAG,
     ISTOBELOCALLYPROCESSED type FLAG,
     ITEMISTOBEPAIDSEPARATELY type FLAG,
     PAYMENTISTOBESENTBYEDI type FLAG,
     HOUSEBANK type C length 5,
     CHECKPAIDDURATIONINDAYS type P length 2 decimals 0,
     CURRENCY type C length 5,
     BILLOFEXCHLMTAMTINCOCODECRCY type P length 8 decimals 3,
     SUPPLIERCLERKIDBYSUPPLIER type C length 12,
     RECONCILIATIONACCOUNT type C length 10,
     INTERESTCALCULATIONCODE type C length 2,
     INTERESTCALCULATIONDATE type TIMESTAMP,
     INTRSTCALCFREQUENCYINMONTHS type C length 2,
     SUPPLIERHEADOFFICE type C length 10,
     ALTERNATIVEPAYEE type C length 10,
     LAYOUTSORTINGRULE type C length 3,
     APARTOLERANCEGROUP type C length 4,
     SUPPLIERCERTIFICATIONDATE type TIMESTAMP,
     SUPPLIERACCOUNTNOTE type C length 30,
     WITHHOLDINGTAXCOUNTRY type C length 3,
     DELETIONINDICATOR type FLAG,
     CASHPLANNINGGROUP type C length 10,
     ISTOBECHECKEDFORDUPLICATES type FLAG,
     MINORITYGROUP type C length 3,
     SUPPLIERACCOUNTGROUP type C length 4,
  end of TS_A_SUPPLIERCOMPANYTYPE .
  types:
TT_A_SUPPLIERCOMPANYTYPE type standard table of TS_A_SUPPLIERCOMPANYTYPE .
  types:
  begin of TS_A_SUPPLIERDUNNINGTYPE,
     SUPPLIER type C length 10,
     COMPANYCODE type C length 4,
     DUNNINGAREA type C length 2,
     DUNNINGBLOCK type C length 1,
     DUNNINGLEVEL type C length 1,
     DUNNINGPROCEDURE type C length 4,
     DUNNINGRECIPIENT type C length 10,
     LASTDUNNEDON type TIMESTAMP,
     LEGDUNNINGPROCEDUREON type TIMESTAMP,
     DUNNINGCLERK type C length 2,
     AUTHORIZATIONGROUP type C length 4,
     SUPPLIERACCOUNTGROUP type C length 4,
  end of TS_A_SUPPLIERDUNNINGTYPE .
  types:
TT_A_SUPPLIERDUNNINGTYPE type standard table of TS_A_SUPPLIERDUNNINGTYPE .
  types:
  begin of TS_A_SUPPLIERPARTNERFUNCTYPE,
     SUPPLIER type C length 10,
     PURCHASINGORGANIZATION type C length 4,
     SUPPLIERSUBRANGE type C length 6,
     PLANT type C length 4,
     PARTNERFUNCTION type C length 2,
     PARTNERCOUNTER type C length 3,
     DEFAULTPARTNER type FLAG,
     CREATIONDATE type TIMESTAMP,
     CREATEDBYUSER type C length 12,
     REFERENCESUPPLIER type C length 10,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_SUPPLIERPARTNERFUNCTYPE .
  types:
TT_A_SUPPLIERPARTNERFUNCTYPE type standard table of TS_A_SUPPLIERPARTNERFUNCTYPE .
  types:
  begin of TS_A_SUPPLIERPURCHASINGORGTEXT,
     SUPPLIER type C length 10,
     PURCHASINGORGANIZATION type C length 4,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_SUPPLIERPURCHASINGORGTEXT .
  types:
TT_A_SUPPLIERPURCHASINGORGTEXT type standard table of TS_A_SUPPLIERPURCHASINGORGTEXT .
  types:
  begin of TS_A_SUPPLIERPURCHASINGORGTYPE,
     SUPPLIER type C length 10,
     PURCHASINGORGANIZATION type C length 4,
     CALCULATIONSCHEMAGROUPCODE type C length 2,
     DELETIONINDICATOR type FLAG,
     INCOTERMSCLASSIFICATION type C length 3,
     INCOTERMSTRANSFERLOCATION type C length 28,
     INCOTERMSVERSION type C length 4,
     INCOTERMSLOCATION1 type C length 70,
     INCOTERMSLOCATION2 type C length 70,
     INVOICEISGOODSRECEIPTBASED type FLAG,
     MATERIALPLANNEDDELIVERYDURN type P length 2 decimals 0,
     MINIMUMORDERAMOUNT type P length 8 decimals 3,
     PAYMENTTERMS type C length 4,
     PRICINGDATECONTROL type C length 1,
     PURORDAUTOGENERATIONISALLOWED type FLAG,
     PURCHASEORDERCURRENCY type C length 5,
     PURCHASINGGROUP type C length 3,
     PURCHASINGISBLOCKEDFORSUPPLIER type FLAG,
     SHIPPINGCONDITION type C length 2,
     SUPPLIERABCCLASSIFICATIONCODE type C length 1,
     SUPPLIERPHONENUMBER type C length 16,
     SUPPLIERRESPSALESPERSONNAME type C length 30,
     SUPPLIERCONFIRMATIONCONTROLKEY type C length 4,
     ISORDERACKNRQD type FLAG,
     AUTHORIZATIONGROUP type C length 4,
     SUPPLIERACCOUNTGROUP type C length 4,
  end of TS_A_SUPPLIERPURCHASINGORGTYPE .
  types:
TT_A_SUPPLIERPURCHASINGORGTYPE type standard table of TS_A_SUPPLIERPURCHASINGORGTYPE .
  types:
  begin of TS_A_SUPPLIERTEXTTYPE,
     SUPPLIER type C length 10,
     LANGUAGE type C length 2,
     LONGTEXTID type C length 4,
     LONGTEXT type string,
  end of TS_A_SUPPLIERTEXTTYPE .
  types:
TT_A_SUPPLIERTEXTTYPE type standard table of TS_A_SUPPLIERTEXTTYPE .
  types:
  begin of TS_A_SUPPLIERTYPE,
     SUPPLIER type C length 10,
     ALTERNATIVEPAYEEACCOUNTNUMBER type C length 10,
     AUTHORIZATIONGROUP type C length 4,
     CREATEDBYUSER type C length 12,
     CREATIONDATE type TIMESTAMP,
     CUSTOMER type C length 10,
     PAYMENTISBLOCKEDFORSUPPLIER type FLAG,
     POSTINGISBLOCKED type FLAG,
     PURCHASINGISBLOCKED type FLAG,
     SUPPLIERACCOUNTGROUP type C length 4,
     SUPPLIERFULLNAME type C length 220,
     SUPPLIERNAME type C length 80,
     VATREGISTRATION type C length 20,
     BIRTHDATE type TIMESTAMP,
     CONCATENATEDINTERNATIONALLOCNO type C length 20,
     DELETIONINDICATOR type FLAG,
     FISCALADDRESS type C length 10,
     INDUSTRY type C length 4,
     INTERNATIONALLOCATIONNUMBER1 type C length 7,
     INTERNATIONALLOCATIONNUMBER2 type C length 5,
     INTERNATIONALLOCATIONNUMBER3 type C length 1,
     ISNATURALPERSON type C length 1,
     RESPONSIBLETYPE type C length 2,
     SUPLRQLTYINPROCMTCERTFNVALIDTO type TIMESTAMP,
     SUPLRQUALITYMANAGEMENTSYSTEM type C length 4,
     SUPPLIERCORPORATEGROUP type C length 10,
     SUPPLIERPROCUREMENTBLOCK type C length 2,
     TAXNUMBER1 type C length 16,
     TAXNUMBER2 type C length 11,
     TAXNUMBER3 type C length 18,
     TAXNUMBER4 type C length 18,
     TAXNUMBER5 type C length 60,
     TAXNUMBERRESPONSIBLE type C length 18,
     TAXNUMBERTYPE type C length 2,
     SUPLRPROOFOFDELIVRLVTCODE type C length 1,
     BR_TAXISSPLIT type FLAG,
     DATAEXCHANGEINSTRUCTIONKEY type C length 2,
  end of TS_A_SUPPLIERTYPE .
  types:
TT_A_SUPPLIERTYPE type standard table of TS_A_SUPPLIERTYPE .
  types:
  begin of TS_A_SUPPLIERWITHHOLDINGTAXTYP,
     SUPPLIER type C length 10,
     COMPANYCODE type C length 4,
     WITHHOLDINGTAXTYPE type C length 2,
     EXEMPTIONDATEBEGIN type TIMESTAMP,
     EXEMPTIONDATEEND type TIMESTAMP,
     EXEMPTIONREASON type C length 2,
     ISWITHHOLDINGTAXSUBJECT type FLAG,
     RECIPIENTTYPE type C length 2,
     WITHHOLDINGTAXCERTIFICATE type C length 25,
     WITHHOLDINGTAXCODE type C length 2,
     WITHHOLDINGTAXEXMPTPERCENT type P length 3 decimals 2,
     WITHHOLDINGTAXNUMBER type C length 16,
     AUTHORIZATIONGROUP type C length 4,
  end of TS_A_SUPPLIERWITHHOLDINGTAXTYP .
  types:
TT_A_SUPPLIERWITHHOLDINGTAXTYP type standard table of TS_A_SUPPLIERWITHHOLDINGTAXTYP .

  constants GC_A_SUPPLIERWITHHOLDINGTAXTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierWithHoldingTaxType' ##NO_TEXT.
  constants GC_A_SUPPLIERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierType' ##NO_TEXT.
  constants GC_A_SUPPLIERTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierTextType' ##NO_TEXT.
  constants GC_A_SUPPLIERPURCHASINGORGTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierPurchasingOrgType' ##NO_TEXT.
  constants GC_A_SUPPLIERPURCHASINGORGTEXT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierPurchasingOrgTextType' ##NO_TEXT.
  constants GC_A_SUPPLIERPARTNERFUNCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierPartnerFuncType' ##NO_TEXT.
  constants GC_A_SUPPLIERDUNNINGTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierDunningType' ##NO_TEXT.
  constants GC_A_SUPPLIERCOMPANYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierCompanyType' ##NO_TEXT.
  constants GC_A_SUPPLIERCOMPANYTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_SupplierCompanyTextType' ##NO_TEXT.
  constants GC_A_CUSTUNLDGPTADDRDEPDNTINFO type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustUnldgPtAddrDepdntInfoType' ##NO_TEXT.
  constants GC_A_CUSTSLSAREAADDRDEPDNTTAXI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustSlsAreaAddrDepdntTaxInfoType' ##NO_TEXT.
  constants GC_A_CUSTSLSAREAADDRDEPDNTINFO type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustSlsAreaAddrDepdntInfoType' ##NO_TEXT.
  constants GC_A_CUSTSALESPARTNERFUNCTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustSalesPartnerFuncType' ##NO_TEXT.
  constants GC_A_CUSTOMERWITHHOLDINGTAXTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerWithHoldingTaxType' ##NO_TEXT.
  constants GC_A_CUSTOMERUNLOADINGPOINTTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerUnloadingPointType' ##NO_TEXT.
  constants GC_A_CUSTOMERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerType' ##NO_TEXT.
  constants GC_A_CUSTOMERTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerTextType' ##NO_TEXT.
  constants GC_A_CUSTOMERTAXGROUPINGTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerTaxGroupingType' ##NO_TEXT.
  constants GC_A_CUSTOMERSALESAREATYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerSalesAreaType' ##NO_TEXT.
  constants GC_A_CUSTOMERSALESAREATEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerSalesAreaTextType' ##NO_TEXT.
  constants GC_A_CUSTOMERSALESAREATAXTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerSalesAreaTaxType' ##NO_TEXT.
  constants GC_A_CUSTOMERDUNNINGTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerDunningType' ##NO_TEXT.
  constants GC_A_CUSTOMERCOMPANYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerCompanyType' ##NO_TEXT.
  constants GC_A_CUSTOMERCOMPANYTEXTTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustomerCompanyTextType' ##NO_TEXT.
  constants GC_A_CUSTADDRDEPDNTINFORMATION type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustAddrDepdntInformationType' ##NO_TEXT.
  constants GC_A_CUSTADDRDEPDNTEXTIDENTIFI type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_CustAddrDepdntExtIdentifierType' ##NO_TEXT.
  constants GC_A_BUSPARTADDRDEPDNTTAXNMBRT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusPartAddrDepdntTaxNmbrType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERTAXNUMBERT type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerTaxNumberType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERROLETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerRoleType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERCONTACTTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerContactType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERBANKTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerBankType' ##NO_TEXT.
  constants GC_A_BUSINESSPARTNERADDRESSTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BusinessPartnerAddressType' ##NO_TEXT.
  constants GC_A_BUPAINDUSTRYTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BuPaIndustryType' ##NO_TEXT.
  constants GC_A_BUPAIDENTIFICATIONTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BuPaIdentificationType' ##NO_TEXT.
  constants GC_A_BUPAADDRESSUSAGETYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BuPaAddressUsageType' ##NO_TEXT.
  constants GC_A_BPCONTACTTOFUNCANDDEPTTYP type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BPContactToFuncAndDeptType' ##NO_TEXT.
  constants GC_A_BPCONTACTTOADDRESSTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BPContactToAddressType' ##NO_TEXT.
  constants GC_A_BPADDRDEPDNTINTLLOCNUMBER type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_BPAddrDepdntIntlLocNumberType' ##NO_TEXT.
  constants GC_A_ADDRESSPHONENUMBERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_AddressPhoneNumberType' ##NO_TEXT.
  constants GC_A_ADDRESSHOMEPAGEURLTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_AddressHomePageURLType' ##NO_TEXT.
  constants GC_A_ADDRESSFAXNUMBERTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_AddressFaxNumberType' ##NO_TEXT.
  constants GC_A_ADDRESSEMAILADDRESSTYPE type /IWBEP/IF_MGW_MED_ODATA_TYPES=>TY_E_MED_ENTITY_NAME value 'A_AddressEmailAddressType' ##NO_TEXT.

  methods GET_EXTENDED_MODEL
  final
    exporting
      !EV_EXTENDED_SERVICE type /IWBEP/MED_GRP_TECHNICAL_NAME
      !EV_EXT_SERVICE_VERSION type /IWBEP/MED_GRP_VERSION
      !EV_EXTENDED_MODEL type /IWBEP/MED_MDL_TECHNICAL_NAME
      !EV_EXT_MODEL_VERSION type /IWBEP/MED_MDL_VERSION
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .
  methods LOAD_TEXT_ELEMENTS
  final
    returning
      value(RT_TEXT_ELEMENTS) type TT_TEXT_ELEMENTS
    raising
      /IWBEP/CX_MGW_MED_EXCEPTION .

  methods DEFINE
    redefinition .
  methods GET_LAST_MODIFIED
    redefinition .
protected section.
private section.
ENDCLASS.



CLASS ZCL_ZAPI_BUSINESS_PART_MPC IMPLEMENTATION.


  method DEFINE.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*


data:
  lo_entity_type    type ref to /iwbep/if_mgw_odata_entity_typ, "#EC NEEDED
  lo_complex_type   type ref to /iwbep/if_mgw_odata_cmplx_type, "#EC NEEDED
  lo_property       type ref to /iwbep/if_mgw_odata_property, "#EC NEEDED
  lo_association    type ref to /iwbep/if_mgw_odata_assoc,  "#EC NEEDED
  lo_assoc_set      type ref to /iwbep/if_mgw_odata_assoc_set, "#EC NEEDED
  lo_ref_constraint type ref to /iwbep/if_mgw_odata_ref_constr, "#EC NEEDED
  lo_nav_property   type ref to /iwbep/if_mgw_odata_nav_prop, "#EC NEEDED
  lo_action         type ref to /iwbep/if_mgw_odata_action, "#EC NEEDED
  lo_parameter      type ref to /iwbep/if_mgw_odata_property, "#EC NEEDED
  lo_entity_set     type ref to /iwbep/if_mgw_odata_entity_set, "#EC NEEDED
  lo_complex_prop   type ref to /iwbep/if_mgw_odata_cmplx_prop. "#EC NEEDED

* Extend the model
model->extend_model( iv_model_name = 'API_BUSINESS_PARTNER' iv_model_version = '0001' ). "#EC NOTEXT

model->set_schema_namespace( 'API_BUSINESS_PARTNER' ).
  endmethod.


  method GET_EXTENDED_MODEL.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*



ev_extended_service  = 'API_BUSINESS_PARTNER'.                "#EC NOTEXT
ev_ext_service_version = '0001'.               "#EC NOTEXT
ev_extended_model    = 'API_BUSINESS_PARTNER'.                    "#EC NOTEXT
ev_ext_model_version = '0001'.                   "#EC NOTEXT
  endmethod.


  method GET_LAST_MODIFIED.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*


  constants: lc_gen_date_time type timestamp value '20240628091635'. "#EC NOTEXT
rv_last_modified = super->get_last_modified( ).
IF rv_last_modified LT lc_gen_date_time.
  rv_last_modified = lc_gen_date_time.
ENDIF.
  endmethod.


  method LOAD_TEXT_ELEMENTS.
*&---------------------------------------------------------------------*
*&           Generated code for the MODEL PROVIDER BASE CLASS          &*
*&                                                                     &*
*&  !!!NEVER MODIFY THIS CLASS. IN CASE YOU WANT TO CHANGE THE MODEL   &*
*&        DO THIS IN THE MODEL PROVIDER SUBCLASS!!!                    &*
*&                                                                     &*
*&---------------------------------------------------------------------*


data:
  lo_entity_type    type ref to /iwbep/if_mgw_odata_entity_typ,           "#EC NEEDED
  lo_complex_type   type ref to /iwbep/if_mgw_odata_cmplx_type,           "#EC NEEDED
  lo_property       type ref to /iwbep/if_mgw_odata_property,             "#EC NEEDED
  lo_association    type ref to /iwbep/if_mgw_odata_assoc,                "#EC NEEDED
  lo_assoc_set      type ref to /iwbep/if_mgw_odata_assoc_set,            "#EC NEEDED
  lo_ref_constraint type ref to /iwbep/if_mgw_odata_ref_constr,           "#EC NEEDED
  lo_nav_property   type ref to /iwbep/if_mgw_odata_nav_prop,             "#EC NEEDED
  lo_action         type ref to /iwbep/if_mgw_odata_action,               "#EC NEEDED
  lo_parameter      type ref to /iwbep/if_mgw_odata_property,             "#EC NEEDED
  lo_entity_set     type ref to /iwbep/if_mgw_odata_entity_set.           "#EC NEEDED


DATA:
     ls_text_element TYPE ts_text_element.                   "#EC NEEDED
  endmethod.
ENDCLASS.
